### ISSUE TITLE
کارایی بهتر با هوش مصنوعی

### ISSUE THREAD

**Issue by ghost** [brothersincode/virastar#1]
با سلام و احترام
ویراستار ایدۀ خوبیست اما کاش از هوش مصنوعی از بهره می‌بردید، همچنین از دیتابیس کلمات فارسی.
برای مثال:
«معادله درجه دومی بنویسید که ریشه‌های آن...»
باید به‌صورت زیر می‌بود:
«معادلۀ درجه دومی بنویسید که ریشه‌های آن...»
یعنی به جای «معادله درجه دوم» که متشکل از ترکیب اضافی است، باید در خروجی بنویسد: «معادلۀ درجۀ دوم».
به طور کلی خیلی عالی می‌شد اگر امکان بهره‌گیری از هوش مصنوعی، ادبیات فارسی و... وجود می‌داشت.
نکتۀ مهم: در اینجا متون (به دلیل LTR بودن درست نمایش داده نمی‌شوند، لطفاً در یک باکس متن راست به چپ این متن را بخوانید)

با تشکر، هادی فرید

**Comment by geminorum** [comment]
<div dir="rtl">
سلام و تشکر

در این مخزن، ما برنامه‌ای برای حرکت به این جهت نداریم. ویراستار یک کتابخانه کم‌حجم و سبک برای اصلاح نویسه‌ها و ترکیب‌های آن‌هاست. مخاطب و هدف اصلی ویراستار هم نرم‌افزارهای جاسازی‌شده در سیستم‌های مدیریت محتوا هستند.

شاید شروع سوء تفاهم، در نام‌گذاری «ویراستار» باشد، که البته کتابخانه منبع که ویراستار از آن شاخه شده، به همین نام بود و ما تلاشی برای تغییر آن نکردیم.

ناگفته نماند، تلاش‌هایی هم در سطوح دیگر در جریان بوده که تا به حال به نتیجه مطلوب نرسیده و نسخه‌ای را منتشر نکردیم. یکی از آن سطوح استفاده از مخزن کلمات فارسی برای پیشنهاد جای‌گزین‌های بهتر برای کلمات و ترکیبات است و در نهایت به صورت کتابخانه مجزا ارائه خواهد شد.
</div>

**Comment by hadifaridhadi** [comment]
بسیار خب ممنونم از پاسخگویی‌تان
